### ISSUE TITLE
Eboluigi Feedback

### ISSUE THREAD

**Issue by BeaterX666** [spartacus04/Eboluigi#1]
[Eboluigi scrive in Zalgo, di default.]
l.insult @ Eboluigi insulta la persona taggata, poi però si scusa perché non vuole essere bannato;
(C'è una probabilità che Eboluigi insulti pesantemente Malario qual'ora quest'ultimo scrivesse in chat, dato che è geloso di suo fratello clone apprezzato dalla plebe).
l.opinion Eboluigi espone una controversa opinione. Meglio non farlo vedere a Freedo.
l.fact Eboluigi decurta i nostri neuroni sparando un fatto totalmente random.

**Comment by spartacus04** [comment]
Farlo scrivere in zalgo di default mi pare molto pesante, penso che inserirò un comando tipo m.say ma con lo zalgo

**Comment by spartacus04** [comment]
Tutto implementato
